services:
  hello:
    container_name: hello_service
    build:
      context: ../services/hello
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - ../../.env
  colmap:
    container_name: colmap_service
    build:
      context: ../services/colmap
      dockerfile: Dockerfile
    runtime: nvidia
    restart: unless-stopped
  3dgrut:
    container_name: 3dgrut_service
    build:
      context: ../../ThirdParty/3dgrut
      dockerfile: Dockerfile
    restart: unless-stopped